-- VHDL module instantiation generated by SCUBA Diamond Version 3.9.1.119
-- Module  Version: 5.7
-- Fri Sep 15 15:45:49 2017

-- parameterized module component declaration
component pll_1
    port (CLKI: in  std_logic; ENCLKOP: in  std_logic; 
        ENCLKOS: in  std_logic; ENCLKOS2: in  std_logic; 
        CLKOP: out  std_logic; CLKOS: out  std_logic; 
        CLKOS2: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll_1
    port map (CLKI=>__, ENCLKOP=>__, ENCLKOS=>__, ENCLKOS2=>__, CLKOP=>__, 
        CLKOS=>__, CLKOS2=>__, LOCK=>__);
